app_name: freshguard-system
mysql:
  host: 192.168.0.122
  port: 3306
  username: root
  password: cfy39177
  database: freshguard
  show_sql: true
nacos:
  host: 192.168.0.122
  port: 8848
  namespace: dev
  group_id: freshguard
  username: nacos
  password: cfy39177
